# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gontainer < Formula
  desc "DI container for GO"
  homepage "https://github.com/gontainer/gontainer"
  version "0.1.0"
  license "MIT"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gontainer/gontainer/releases/download/v0.1.0/gontainer_Darwin_x86_64.tar.gz"
      sha256 "136442760a4cfcfdc0db12556e044ac97b8928dc7c83a516a631c54706b7426b"

      def install
        bin.install "gontainer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gontainer/gontainer/releases/download/v0.1.0/gontainer_Darwin_arm64.tar.gz"
      sha256 "566ebbe45ccfa9569bae0128213d9d9dfc740634f568f96af28a5d1f65b00b8b"

      def install
        bin.install "gontainer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gontainer/gontainer/releases/download/v0.1.0/gontainer_Linux_x86_64.tar.gz"
      sha256 "be89a154c18014932ff1ab7b0e3cc1aa0450af14315636c0857a006f0b7c7085"

      def install
        bin.install "gontainer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gontainer/gontainer/releases/download/v0.1.0/gontainer_Linux_armv7.tar.gz"
      sha256 "cb225617b9e8245ec87062f829f16a2db1de55ffee8af0cf6766eaa9b8b92e56"

      def install
        bin.install "gontainer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gontainer/gontainer/releases/download/v0.1.0/gontainer_Linux_arm64.tar.gz"
      sha256 "e78c1c9c047539bfa91331edd436a94137c128b661783b89827aa3650aaea396"

      def install
        bin.install "gontainer"
      end
    end
  end

  test do
    system "#{bin}/gontainer -v"
  end
end
