name: Gontainer

on:
  push:
    branches:
      - main

jobs:

  bootstrapping:
    env:
      COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"
    if: ${{ startsWith(github.event.head_commit.message, 'Brew formula update for gontainer version') }}
    name: Bootstrapping PR
    runs-on: macos-latest
    steps:
      - run: echo "GONTAINER_VERSION=$(echo $COMMIT_MESSAGE | awk '{print $NF}')" >> $GITHUB_ENV
      - run: echo "Gontainer $GONTAINER_VERSION"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: gontainer/gontainer
          token: ${{ secrets.RELEASES_TOKEN }}

      - run: git checkout -B bootstrapping/$GONTAINER_VERSION
      - run: brew install gontainer/homebrew-tap/gontainer
      - run: gontainer -v
      - run: make self-compile
      - run: "git config user.name 'github-actions[bot]'"
      - run: "git config user.email 'github-actions[bot]@users.noreply.github.com'"
      - run: 'git commit -m "feat(bootstrapping): gontainer $GONTAINER_VERSION" internal/gontainer/gontainer.go'
      - run: "git push --set-upstream origin bootstrapping/$GONTAINER_VERSION"
      - name: Create pull request
        run: 'gh pr create --base=main --body="Automatically rebuild dependencies 🤖" --fill-first --no-maintainer-edit'
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
